name: Pull requests check

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          sudo apt-get install -y postgresql-client
          until pg_isready -h localhost -p 5432 -U postgres; do
            sleep 1
          done
          psql -h localhost -p 5432 -U postgres -c 'CREATE DATABASE test;'
        env:
          PGPASSWORD: postgres
      - run: bun i --no-cache
      - run: npx prisma db push
      - run: bun run lint
      - run: bun run lint:types
      - run: bun run test
